package com.objectstyle.bq_demo.cayenne.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.objectstyle.bq_demo.cayenne.Artist;

/**
 * Class _Exhibit was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Exhibit extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Date> ENDS = new Property<Date>("ends");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> PLACE = new Property<String>("place");
    public static final Property<Date> STARTS = new Property<Date>("starts");
    public static final Property<List<Artist>> ARTISTS = new Property<List<Artist>>("artists");

    public void setEnds(Date ends) {
        writeProperty("ends", ends);
    }
    public Date getEnds() {
        return (Date)readProperty("ends");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPlace(String place) {
        writeProperty("place", place);
    }
    public String getPlace() {
        return (String)readProperty("place");
    }

    public void setStarts(Date starts) {
        writeProperty("starts", starts);
    }
    public Date getStarts() {
        return (Date)readProperty("starts");
    }

    public void addToArtists(Artist obj) {
        addToManyTarget("artists", obj, true);
    }
    public void removeFromArtists(Artist obj) {
        removeToManyTarget("artists", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Artist> getArtists() {
        return (List<Artist>)readProperty("artists");
    }


}
